appId: com.chronos.app
productName: Chronos
copyright: Copyright © 2025 Chronos Team

directories:
  output: dist/electron
  buildResources: resources

files:
  - dist/**/*
  - package.json
  - node_modules/**/*

mac:
  category: public.app-category.developer-tools
  target:
    - dmg
    - zip
  icon: resources/icon.icns
  minimumSystemVersion: "10.13.0"

win:
  target:
    - nsis
    - portable
  icon: resources/icon.ico

linux:
  target:
    - AppImage
    - deb
  category: Development
  icon: resources/icon.png

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true

publish:
  provider: github
  owner: steven780-sudo
  repo: vibecoding
